### ISSUE TITLE
Use embedded metadata 

### ISSUE THREAD

**Issue by MRodneyMcKay** [patrickkfkan/volumio-now-playing#10]
I have a properly tagged library,  would it be possible to use the embedded lyrics tag?

**Comment by patrickkfkan** [comment]
Closing this issue as Now Playing now queries the active music service plugin for lyrics, before resorting to LRCLIB / Genius. If the queried plugin implements the [NowPlayingMetadataProvider](https://github.com/patrickkfkan/volumio-now-playing-common/blob/master/src/external/NowPlayingMetadataProvider.ts) interface, then Now Playing will display lyrics returned by the plugin. 

If songs are played from Volumio's Music Library, then embedded lyrics tag will not be shown. This is because the MPD plugin does not implement the aforesaid interface. The closest thing one can do to get embedded lyrics is to install [Jellyfin](https://jellyfin.org/) server (10.9.x onward supports lyrics tag and `.lrc` files) + Jellyfin plugin.
